import { ProductItem } from "@/types/products";

export const products: ProductItem[] = [
  {
    id: 1,
    name: "Смартфон",
    brand: "Apple",
    model: "iPhone ",
    memory: "128GB",
    img: ["/iphone2.png", "/hiaomi1.png", "/iphone3.png"],
    price: 87999,
    newModel: true,
    quantity: 4,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
  },
  {
    id: 2,
    name: "Смартфон",
    brand: "Apple",
    model: "iPhone 12",
    memory: "64GB",
    img: ["/hiaomi1.png", "/iphone3.png", "/iphone2.png"],
    price: 47756,
    discount: 10,
    quantity: 4,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
  },
  {
    id: 3,
    name: "Смартфон",
    brand: "HUAWEI",
    model: "nova Y61",
    memory: "128GB",
    img: ["/iphone3.png", "/hiaomi1.png", "/iphone2.png"],
    price: 14117,
    discount: 15,
    quantity: 4,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
  },
  {
    id: 4,
    name: "Смартфон",
    brand: "Xiaomi",
    model: "Redmi",
    memory: "128GB",
    img: ["/hiaomi1.png", "/iphone2.png", "/iphone3.png"],
    price: 87999,
    discount: 80,
    quantity: 4,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
  },
  {
    id: 5,
    name: "Смартфон",
    brand: "Apple",
    model: "iPhone 14",
    memory: "128GB",
    img: ["/hiaomi1.png", "/iphone2.png", "/iphone3.png"],
    price: 84999,
    quantity: 4,

    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
  },
  {
    id: 6,
    name: "Смартфон",
    brand: "HUAWEI",
    model: "nova Y61",
    memory: "128GB",
    img: ["/hiaomi1.png", "/iphone2.png", "/iphone3.png"],
    price: 14117,
    quantity: 4,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
  },
  {
    id: 7,
    name: "Смартфон",
    brand: "Xiaomi",
    model: "Redmi",
    memory: "128GB",
    quantity: 4,
    newModel: true,
    img: ["/hiaomi1.png", "/iphone2.png", "/iphone3.png"],
    price: 87999,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
  },
  {
    id: 8,
    name: "Смартфон",
    brand: "Apple",
    model: "iPhone 14",
    memory: "128GB",
    quantity: 4,
    img: ["/hiaomi1.png", "/iphone2.png", "/iphone3.png"],
    price: 84999,
    discount: 4,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
  },
  {
    id: 9,
    name: "Смартфон",
    brand: "HUAWEI",
    model: "nova Y61",
    memory: "128GB",
    quantity: 4,

    img: ["/hiaomi1.png", "/iphone2.png", "/iphone3.png"],
    price: 14117,
    discount: 15,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
  },
  {
    id: 10,
    name: "Смартфон",
    brand: "Xiaomi",
    model: "Redmi",
    quantity: 4,
    newModel: true,
    memory: "128GB",
    img: ["/hiaomi1.png", "/iphone2.png", "/iphone3.png"],
    price: 87999,
    discount: 80,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
  },

  {
    id: 26,
    brand: "Apple",
    model: "iPhone 14",
    memory: "128GB",
    img: ["/nout1.png", "/nout2.png", "/nout3.png"],
    price: 87999,
    discount: 4,
    quantity: 4,
    name: "Ноутбук",
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
  },
  {
    id: 27,
    brand: "Apple",
    model: "iPhone  12 ",
    memory: "64GB",
    img: ["/nout2.png", "/nout3.png", "/nout4.png"],
    price: 47756,
   newModel:true,
    quantity: 4,
    name: "Ноутбук",
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
  },
  {
    id: 28,
    brand: "HUAWEI",
    model: "nova Y61",
    memory: "128GB",
    img: ["/nout4.png", "/nout6.png", "/nout1.png"],
    price: 14117,
    
    quantity: 4,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 29,
    brand: "Xiaomi",
    model: "Redmi",
    memory: "128GB",
    img: ["/nout2.png", "/nout6.png", "/nout1.png"],
    price: 87999,
    discount: 80,
    quantity: 4,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 30,
    brand: "Apple",
    model: "iPhone 14",
    memory: "128GB",
    img: ["/nout4.png", "/nout6.png", "/nout1.png"],
    price: 84999,
   
    quantity: 4,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 31,
    brand: "HUAWEI",
    model: "nova Y61",
    memory: "128GB",
    img: ["/nout5.png", "/nout6.png", "/nout1.png"],
    price: 14117,
    quantity: 4,

    newModel:true,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 32,
    brand: "Xiaomi",
    model: "Redmi",
    memory: "128GB",
    quantity: 4,

    img: ["/nout2.png", "/nout6.png", "/nout1.png"],
    price: 87999,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 33,
    brand: "Apple",
    model: "iPhone 14",
    memory: "128GB",
    quantity: 4,

    img: ["/nout4.png", "/nout6.png", "/nout1.png"],
    price: 84999,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 34,
    brand: "HUAWEI",
    model: "nova Y61",
    memory: "128GB",
    quantity: 4,

    img: ["/nout3.png", "/nout6.png", "/nout1.png"],
    price: 14117,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 35,
    brand: "Xiaomi",
    model: "Redmi",
    quantity: 4,

    memory: "128GB",
    img: ["/nout2.png", "/nout6.png", "/nout1.png"],
    price: 87999,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
  {
    id: 36,
    brand: "Apple",
    model: "iPhone 14",
    quantity: 4,

    memory: "128GB",
    img: ["/nout3.png", "/nout6.png", "/nout1.png"],
    price: 84999,
    discount: 4,
    characteristic: {
      screen: '6.1"/2532x1170',
      cores: "6",
      power: "20W",
      ram: "6GB",
      rom: "128GB",
      camera: "64/2 MP",
    },
    name: "Ноутбук",
  },
];
